#!/usr/bin/env php
<?php
mkdir('app', 0700);
mkdir('app/controller', 0700);
mkdir('app/controller/test', 0700);
mkdir('app/model', 0700);
mkdir('app/data', 0700);
$controller_base = <<< EOF
<?php
class controller_base {
        public function run() {
                echo "@".date('Y-m-d H:i:s')."\n";
        }
}
EOF;
file_put_contents('app/controller/base.php', $controller_base);

$controller_test = '
<?php
class controller_test_a extends controller_base {

        public function index() {
                $this->run();
        }
}
';
file_put_contents('app/controller/test/a.php', $controller_test);

